// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace carrinho.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dominio.Motores", b =>
                {
                    b.Property<int>("IdMotores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMotores");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMotores"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("Estado");

                    b.Property<string>("NomeMotores")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeMotores");

                    b.Property<int>("Rotacao")
                        .HasColumnType("int")
                        .HasColumnName("Rotacao");

                    b.HasKey("IdMotores");

                    b.ToTable("Motores", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
