// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace procafeiro.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dominio.Panha", b =>
                {
                    b.Property<int>("IdPanha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPanha");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPanha"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<int>("Nlitros")
                        .HasColumnType("int")
                        .HasColumnName("Nlitros");

                    b.Property<int>("Nmedidas")
                        .HasColumnType("int")
                        .HasColumnName("Nmedidas");

                    b.Property<string>("NomeColobarador")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeColobarador");

                    b.HasKey("IdPanha");

                    b.ToTable("Panhas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
